# Generated by Django 4.0.3 on 2022-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='hehe', upload_to='images'),
            preserve_default=False,
        ),
    ]
